identity:
  name: email
  author: flowerwine
  label:
    en_US: Email Sender
    zh_Hans: 邮件发送
description:
  human:
    en_US: Send email via Resend
    zh_Hans: 通过 Resend 发送邮件
  llm: 通过 Resend 发送邮件
parameters:
  - name: api_key
    type: string
    required: true
    form: form
    label:
      en_US: Resend API Key
      zh_Hans: Resend API Key
    human_description:
      en_US: Enter your Resend API Key
      zh_Hans: 输入你的 Resend API Key
    is_secret: true
  
  - name: from_email
    type: string
    required: true
    form: form
    label:
      en_US: From Email
      zh_Hans: 发件人邮箱
    human_description:
      en_US: Enter sender email address
      zh_Hans: 输入发件人邮箱地址
  
  - name: to_email
    type: string
    required: true
    form: llm
    label:
      en_US: To Email
      zh_Hans: 收件人邮箱
    human_description:
      en_US: Enter recipient email address
      zh_Hans: 输入收件人邮箱地址

  - name: subject
    type: string
    required: true
    form: llm
    label:
      en_US: Email Subject
      zh_Hans: 邮件主题
    human_description:
      en_US: Enter email subject
      zh_Hans: 输入邮件主题

  - name: content
    type: string
    required: true
    form: llm
    label:
      en_US: Email Content
      zh_Hans: 邮件内容
    human_description:
      en_US: Enter email content
      zh_Hans: 输入邮件内容

extra:
  python:
    source: tools/email/email.py