name: Hello Github
parameters:
  title:
    type: string
    required: true
    label: 文章标题
  content:
    type: string
    required: true
    label: 正文内容
  author:
    type: string
    required: false
    label: 作者
  cover_image:
    type: string
    required: false
    label: 封面图片URL