identity:
  name: toutiao
  author: flowerwine
  label:
    en_US: Toutiao Article
    zh_Hans: 头条文章发布
description:
  human:
    en_US: Publish article to Toutiao
    zh_Hans: 发布文章到今日头条（今日头条接口未破解）
  llm: 发布文章到今日头条平台
parameters:
  - name: cookies
    type: string
    required: true
    form: form
    label:
      en_US: Toutiao Cookies
      zh_Hans: 头条 Cookies
    human_description:
      en_US: Enter your Toutiao cookies
      zh_Hans: 输入你的头条 cookies
    is_secret: true
  
  - name: title
    type: string
    required: true
    form: llm
    label:
      en_US: Article Title
      zh_Hans: 文章标题
    human_description:
      en_US: Enter article title
      zh_Hans: 输入文章标题

  - name: content
    type: string
    required: true
    form: llm
    label:
      en_US: Article Content
      zh_Hans: 文章内容
    human_description:
      en_US: Enter article content
      zh_Hans: 输入文章内容

  - name: cover_image
    type: string
    required: false
    form: llm
    label:
      en_US: Cover Image URL
      zh_Hans: 封面图片链接
    human_description:
      en_US: Enter cover image URL
      zh_Hans: 输入封面图片链接

extra:
  python:
    source: tools/toutiao/toutiao.py