identity:
  name: feishu
  author: flowerwine
  label:
    en_US: Feishu Message
    zh_Hans: 飞书消息通知
description:
  human:
    en_US: Send Message to Feishu
    zh_Hans: 发送消息通知给飞书的指定用户
  llm: 发送消息通知给飞书的指定用户
parameters:
  - name: app_id
    type: string
    required: true
    form: form
    label:
      en_US: Feishu App ID
      zh_Hans: 飞书应用 AppID
    human_description:
      en_US: Enter your Feishu App ID
      zh_Hans: 输入你的飞书应用 AppID
  
  - name: app_secret
    type: string
    required: true
    form: form
    label:
      en_US: Feishu App Secret
      zh_Hans: 飞书应用 AppSecret
    human_description:
      en_US: Enter your Feishu App Secret
      zh_Hans: 输入你的飞书应用 AppSecret
    is_secret: true
    
  - name: user_id
    type: string
    required: true
    form: form
    label:
      en_US: User ID
      zh_Hans: 用户 ID
    human_description:
      en_US: Enter user ID
      zh_Hans: 输入用户 ID

  - name: message
    type: string
    required: true
    form: llm
    label:
      en_US: Message Content
      zh_Hans: 消息内容
    human_description:
      en_US: Enter message content
      zh_Hans: 输入要发送的消息内容

extra:
  python:
    source: tools/feishu/feishu.py